spring: 
  profiles:
    active:
    - dev
---
server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.hrt.springcloud.vo          # 所有vo别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
  
spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8          # 数据库名称
    username: root
    password: "0314"
    dbcp2: 
      min-idle: 5                                       # 数据库连接池最小维持连接数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接获取最大超时时间
    
eureka:
  client: # 客户端注册到eureka内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true #访问路径可以显示ip地址 
    
info: 
  app.name: hrt
  company.name: www.hrt.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.hrt.springcloud.vo          # 所有vo别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
  
spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02?useUnicode=true&characterEncoding=utf-8          # 数据库名称
    username: root
    password: "0314"
    dbcp2: 
      min-idle: 5                                       # 数据库连接池最小维持连接数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接获取最大超时时间
    
eureka:
  client: # 客户端注册到eureka内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true #访问路径可以显示ip地址 
    
info: 
  app.name: hrt
  company.name: www.hrt.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$